microservice-chart:
  namespace: tls

  image:
    repository: ghcr.io/pagopa/infra-ssl-check
    tag: 1.2.1

  sidecars:
    - name: azurite
      securityContext:
        allowPrivilegeEscalation: false
      image: mcr.microsoft.com/azure-storage/azurite:3.18.0@sha256:fbd99a4aa4259827081ff9e5cd133a531f20fa2d1d010891fd474d5798f15d7a
      ports:
        - containerPort: 10000
      resources:
        limits:
          memory: 100Mi
          cpu: 100m

  ingress:
    create: false

  service:
    create: false

  resources:
    requests:
      memory: 20Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 1000m

  envConfig:
    WEBSITE_SITE_NAME: "https://pagopa.it" # TODO - Check if it is working
    FUNCTION_WORKER_RUNTIME: dotnet
    TIME_TRIGGER: "0 * * * * *" # TODO - Once every 30'
    FunctionName: "https://pagopa.it" # TODO - make this not mandatory, use Host as default
    Region: West Europe
    ExpirationDeltaInDays: 15
    Host: "https://pagopa.it"
    AzureWebJobsStorage: "UseDevelopmentStorage=true"

  envSecret:
    APPINSIGHTS_INSTRUMENTATIONKEY: infra-tls-check-appinsights-instrumentationkey

  keyvault:
    name: dvopla-d-neu-kv
    tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
